spring:
  application:
    name: order
  datasource:
    username: root
    password: zhangke12289
    url: jdbc:mysql://180.76.172.198/sell?characterEncoding=utf-8&useSSL=false
eureka:
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/
server:
  port: 8712
PRODUCT:
  riboon:
    NFLoadBalancerRuleClassName: com.netflix.loadbancer.RandomRule
